name: "Danger Swift"
on: [pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.2.0

      - name: Install Danger js
        run: npm install -g danger@12.0.0

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Build
        working-directory: LocalPackage
        run: swift build

      - name: Danger
        working-directory: LocalPackage
        run: swift run danger-swift ci --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
